// Nhân sự Lộc Trời — 5 sub-role tương ứng từng bước trong quy trình A1 → B5
// Mỗi nhân sự có chỉ số KPI cá nhân riêng, được cập nhật real-time khi họ tác nghiệp.

export const LT_SUBROLES = {
  manager: {
    code: "manager",
    label: "Quản lý cấp Vùng",
    icon: "👔",
    desc: "Duyệt yêu cầu vật tư, theo dõi KPI mạng lưới, quản lý invoice & SCF.",
    color: "from-blue-500 to-indigo-600",
    bg: "bg-blue-50",
    text: "text-blue-700",
    tabs: ["managerHome", "overview", "farmers", "invoices"],
  },
  fieldOfficer: {
    code: "fieldOfficer",
    label: "Cán bộ 3 Cùng",
    icon: "🧑‍🌾",
    desc: "Onboard nông dân (A1/A2), tick checklist SRP thực địa (B4) sau khi drone bay.",
    color: "from-emerald-500 to-green-600",
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    tabs: ["officerHome", "onboarding", "inspection"],
  },
  droneOperator: {
    code: "droneOperator",
    label: "Phi công Drone",
    icon: "🚁",
    desc: "Bay drone DJI, upload ảnh đa phổ — AI tự chấm điểm phủ xanh & NDVI (B4.1-B4.2).",
    color: "from-sky-500 to-cyan-600",
    bg: "bg-sky-50",
    text: "text-sky-700",
    tabs: ["droneHome", "droneUpload"],
  },
  driver: {
    code: "driver",
    label: "Tài xế giao vật tư",
    icon: "🚛",
    desc: "Quét QR Hộ chiếu Số nông dân, ký số xác nhận giao vật tư trên blockchain (B3).",
    color: "from-amber-500 to-orange-500",
    bg: "bg-amber-50",
    text: "text-amber-700",
    tabs: ["driverHome", "delivery"],
  },
  procurement: {
    code: "procurement",
    label: "Cán bộ thu mua",
    icon: "🌾",
    desc: "Cuối vụ: cân lúa, tất toán bao tiêu + Premium SRP, cập nhật Credit Score (B5).",
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-50",
    text: "text-rose-700",
    tabs: ["procurementHome", "harvest"],
  },
};

export const SUBROLE_ORDER = ["manager", "fieldOfficer", "droneOperator", "driver", "procurement"];

export const initialStaff = [
  {
    id: "LT-MGR-001",
    subrole: "manager",
    hoTen: "Nguyễn Quốc Tuấn",
    chucDanh: "Giám đốc Vùng ĐBSCL",
    khuVuc: "Toàn vùng — An Giang, Cần Thơ, Kiên Giang, Đồng Tháp",
    ngayVaoLam: "2018-03-15",
    kpi: { hopDongDuyet: 0, doanhThuVuMua: 0, soLanDuyet: 0 },
  },
  {
    id: "LT-FO-002",
    subrole: "fieldOfficer",
    hoTen: "Trần Minh Đức",
    chucDanh: "Cán bộ 3 Cùng — Khu Thoại Sơn",
    khuVuc: "Thoại Sơn, Châu Phú — An Giang",
    ngayVaoLam: "2021-06-01",
    kpi: { hoOnboard: 0, soLanKiemTra: 0, srpDiemTrungBinh: 0 },
  },
  {
    id: "LT-FO-003",
    subrole: "fieldOfficer",
    hoTen: "Lê Thị Hồng",
    chucDanh: "Cán bộ 3 Cùng — Khu Cần Thơ",
    khuVuc: "Vĩnh Thạnh, Cờ Đỏ — Cần Thơ",
    ngayVaoLam: "2022-09-12",
    kpi: { hoOnboard: 0, soLanKiemTra: 0, srpDiemTrungBinh: 0 },
  },
  {
    id: "LT-DO-004",
    subrole: "droneOperator",
    hoTen: "Phạm Văn Khoa",
    chucDanh: "Phi công Drone DJI Agras T40",
    khuVuc: "Đội bay 1 — ĐBSCL",
    ngayVaoLam: "2023-01-08",
    kpi: { soLanBay: 0, anhUpload: 0, dienTichQuet: 0 },
  },
  {
    id: "LT-DR-005",
    subrole: "driver",
    hoTen: "Hoàng Văn Sang",
    chucDanh: "Tài xế giao vật tư",
    khuVuc: "Đội xe Long Xuyên",
    ngayVaoLam: "2020-04-20",
    kpi: { donGiao: 0, kmDiChuyen: 0 },
  },
  {
    id: "LT-PR-006",
    subrole: "procurement",
    hoTen: "Vũ Thị Lan",
    chucDanh: "Cán bộ thu mua lúa & tất toán",
    khuVuc: "Trạm thu mua An Giang",
    ngayVaoLam: "2019-11-03",
    kpi: { tanLuaThuMua: 0, hopDongTatToan: 0, premiumChi: 0 },
  },
];
